name: wax
description: A comic reader.
publish_to: 'none'

version: 1.3.9+15

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  protobuf: ^2.0.1
  url_launcher: ^6.1.2
  flutter_styled_toast: ^2.0.0
  permission_handler: ^10.1.0
  flutter_colorpicker: ^1.0.3
  crypto: ^3.0.2
  event: ^2.1.2
  convert: ^3.0.1
  modal_bottom_sheet: ^3.0.0-pre
  clipboard: ^0.1.3
  photo_view: ^0.14.0
  flutter_svg: ^1.0.3
  another_xlider: ^1.0.1+2
  scrollable_positioned_list: ^0.2.0-nullsafety.0
  flutter_search_bar: ^3.0.0-dev.1
  file_picker: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/assets/
