[package]
name = "wast"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
image = "0.25.6"
rust2go = "0.4.1"

[build-dependencies]
rust2go = { version = "0.4.1", features = ["build"] }
